### ISSUE TITLE
Let createEditor parse a string

### ISSUE THREAD

**Issue by fvanwijk** [xavi-/node-properties-parser#10]
Currently, `createEditor` only supports reading files just like `read`, while there is a `parse` method for parsing a string. I'd like to have a method that initializes an `Editor` passing a parsed string in the constructor.
This is more convenient than creating an empty `Editor` and calling `set` in a loop.

**Comment by xavi-** [comment]
Seems reasonable.  Created a `editorFromString` method in [`0.6.0`](https://www.npmjs.com/package/properties-parser/v/0.6.0).
