### ISSUE TITLE
Specify file encoding as utf-8

### ISSUE THREAD

**Issue by Nolski** [xavi-/node-properties-parser#13]
.properties files are generally supposed to be encoded as utf-8 so explicitly stating this in `fs.readFile` and bubbling up an error if not might be a good idea?

**Comment by apolci** [comment]
".properties" file should be encoded with ISO-8859-1 and use the unicode escape characters  (\uHHHH) for non Latin-1 characters. At least this is the specification of the format for java, but I don't think there are different specification for the format.

**Comment by apolci** [comment]
Sorry I just noticed that also the java specification changed in java 9, now the default encoding is UTF-8 with fallback to ISO-8859-1 if a non-UTF-8 character is encountered: http://openjdk.java.net/jeps/226

**Comment by xavi-** [comment]
Seems reasonable.  Specified read encoding on [`0.5.1`](https://www.npmjs.com/package/properties-parser/v/0.5.1)
