### ISSUE TITLE
Keys with escaped newlines parsed improperly

### ISSUE THREAD

**Issue by sceutre** [xavi-/node-properties-parser#16]
Hi there, if you have a properties file that looks like:
```
foo\
    foo=bar\
        bar
```
Then according to the Java spec (and actual Java implementation) you should get `{"foofoo":"barbar"}`.  But currently you get `{"foo\n   foo":"barbar"}`

What you should be doing is put the following in the start of the while loop in consumeKey (just like it is in consumeVal)
```
      if (startsLineBreak(iter)) {
         children.push(consumeLineBreak(iter));
         continue;
      }
```

Cheers and thanks for the lib, it's a surprising edge-casey format to parse.

**Comment by xavi-** [comment]
Good call.  Thank you.  Fixed in [`0.5.0`](https://www.npmjs.com/package/properties-parser/v/0.5.0)
