### ISSUE TITLE
Adding TypeScript support ?

### ISSUE THREAD

**Issue by iaravindreddyp** [xavi-/node-properties-parser#19]
I was searching for the @types for this package i couldn't find it may it will be helpful if we could add typescript support or at-least have the types file

**Comment by reuschj** [comment]
This 👆

**Comment by segevfiner** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63544

**Comment by segevfiner** [comment]
Available now https://www.npmjs.com/package/@types/properties-parser

**Comment by xavi-** [comment]
Thank you!  Added link to README
