### ISSUE TITLE
Support for tree output

### ISSUE THREAD

**Issue by fvanwijk** [xavi-/node-properties-parser#9]
Usually property files have a hierarchical key structure, ie:

```
parent.childA=value1
parent.childB=value2
```

Could you add a config parameter to set a delimiter so that the output will be:

```
{
  parent: {
    childA: value1,
    childB: value2
  }
}
```

In this case the delimiter is `.`

**Comment by crissdev** [comment]
:+1: It would be great to have this feature.

**Comment by xavi-** [comment]
That would be interesting though I hesitate to implement it for the following reasons:

- Java's property parser doesn't have this functionality
- I'm not sure how the editor object would support this feature
- This would be a breaking change, so it cannot be default behavior

All these issues are surmountable, but I'm not sure if it's worth while.  Perhaps a small post-processing step could achieve similar results?
